export const defaultTheme = {
  colors: {
    'white': '#fff',
    'black': '#000',
    'headline': '#22262a', 
    'paragraph': '#484f56', 
    'brand-beige': '#fffaf0', 
    'green-primary': '#008537',
    'green-primary-dark': "#00471e",
    'bg-light': '#f0fef8', 
    'brand-greenlight': '#c9fddf',
    'bg-dark': '#00471e', 
    "base-button": "#E6E5E5",
    "base-background": "#FAFAFA",
    "base-card": "#F3F2F2",
    "base-input": "#EDEDED",
    "base-hover": "#D7D5D5",
    "base-label": "#8D8686",
    "base-text": "#574F4D",
    "base-subtitle": "#403937",
    "base-title": "#272221",
    "base-error": "#f84747",
},
  textSizes : {
    "title-s": "3rem",
    "title-m": "1.6rem",
    "title-l": "2.6rem",
    "text-regular-m": "1.4rem",
    "text-regular-l": "1.8rem",
    "text-regular-xl": "2rem",
  }
}
